version: "3.4"

services:

    redis:
        image: redis:6.0.3

    web:
        build:
            context: ..
            dockerfile: Dockerfile.backend
        volumes:
            - ..:/code/ASeniorIsAsking:z
        ports:
            - "5000:5000"
        environment:
            - PYTHONPATH=.
        depends_on:
            - redis
        command: python3 /code/ASeniorIsAsking/backend/src/app.py
